### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'Env')

### ISSUE THREAD

**Issue by jasondamour** [devcontainers/cli#992]
Getting this error suddenly from CLI/Vscode/Cursor:
```
➜  devcontainer build --workspace-folder . --config .devcontainer/devcontainer.json --image-name=test
[3 ms] @devcontainers/cli 0.75.0. Node.js v20.12.2. darwin 24.3.0 arm64.
TypeError: Cannot read properties of null (reading 'Env')
    at o6 (/Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:393:20372)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async y6 (/Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:467:2352)
    at async dw (/Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:467:1886)
    at async R7 (/Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:667:2203)
    at async S7 (/Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:666:4937)
    at async /Users/jasondamour/.nvm/versions/node/v20.12.2/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:484:1188
{"outcome":"error","message":"Cannot read properties of null (reading 'Env')","description":"An error occurred building the container."}
```

With the dockerfile:
```
FROM mcr.microsoft.com/devcontainers/base:1.2-ubuntu-22.04
```

Given I haven't upgraded the CLI in a while and this was working fine recently, I believe this is caused by a change to the base Docker image. Semi-confirmed by changing my base image to `ubuntu:22.04` and it worked fine.

However, going to use this repo for the issue. If an image doesn't have an `Env` property, shouldn't the CLI still succeed?

**Comment by v-Kaniska244** [comment]
Hello @jasondamour ,

Thank you for reporting this issue. 
Would you kindly add `--log-level` as `trace` on the `devcontainer build` command and share the output? Also it would be great if you could share the devcontainer.json and Dockerfile/ docker-compose.yml used in this scenario as that would help us a to investigate this problem further. I have tried reproducing the same in Mac locally on VS code, but it doesn't seem to be happening for me.

With Regards,
Kaniska

**Comment by v-Kaniska244** [comment]
Closing this issue presuming it has been fixed for the user. Kindly reopen otherwise.

**Comment by jshbrntt** [comment]
@Kaniska244 this is still an issue.

The `devcontainers/cli` is calling `docker inspect --type image ...` as part of this [function](https://github.com/devcontainers/cli/blob/e47ebf9caf99f48ad28571c7e50e9a56eef01c55/src/spec-shutdown/dockerUtils.ts#L137-L155).

The JSON object returned by this CLI command is defined by the type `image.InspectResponse` (in `moby`) and there is no `Env` property on this type.

https://github.com/moby/moby/blob/master/api/types/image/image_inspect.go#L17-L108

Therefore the assumption in [this line of code](https://github.com/devcontainers/cli/blob/e47ebf9caf99f48ad28571c7e50e9a56eef01c55/src/spec-node/imageMetadata.ts#L408) that this property always exists is false and a bug.

**Comment by v-Kaniska244** [comment]
Hi @jshbrntt ,

Thank you for further details. I will check and get back to you.
